# Generated by Django 2.2.6 on 2019-12-20 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='date',
            new_name='buy',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='company',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='price',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='sell',
            field=models.DateField(default='2019-12-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='ticker',
            field=models.CharField(default='AAPL', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
