# Generated by Django 2.2.6 on 2020-01-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191220_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='user',
        ),
        migrations.AddField(
            model_name='performance',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Company'),
            preserve_default=False,
        ),
    ]
